# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# Selects the standalone Elastic collector configuration after the upstream
# full and observability layers have been applied.
services:
  otel-collector:
    command:
      - --config=/etc/otelcol-config.yml
      - --config=/etc/otelcol-config-extras.yml
    environment:
      - ELASTIC_OTLP_ENDPOINT
      - ELASTIC_OTLP_API_KEY
