collectors:
    daemon:
      config:
        processors:
          k8sattributes:
            filter:
              node_from_env_var: OTEL_K8S_NODE_NAME
            passthrough: false
            pod_association:
              - sources:
                  - from: resource_attribute
                    name: k8s.pod.ip
              - sources:
                  - from: resource_attribute
                    name: k8s.pod.uid
              - sources:
                  - from: connection
            extract:
              metadata:
                - "k8s.namespace.name"
                - "k8s.deployment.name"
                - "k8s.replicaset.name"
                - "k8s.statefulset.name"
                - "k8s.daemonset.name"
                - "k8s.cronjob.name"
                - "k8s.job.name"
                - "k8s.node.name"
                - "k8s.pod.name"
                - "k8s.pod.ip"
                - "k8s.pod.uid"
                - "k8s.pod.start_time"
                - "container.id"              # <-- added
                - "service.name"
                - "service.version"
                - "service.instance.id"
        service:
          pipelines:
            traces/apm:
              receivers:
                - otlp
              processors:
                - k8sattributes           # <-- added
                - batch
                - resource/hostname
              exporters:
                - otlp/gateway
            logs/apm:
              receivers:
                - otlp
              processors:
                - k8sattributes           # <-- added
                - batch
                - resource/hostname
              exporters:
                - otlp/gateway
            metrics/otel-apm:
              receivers:
                - otlp
              processors:
                - k8sattributes           # <-- added
                - batch/metrics
                - resource/hostname
              exporters:
                - otlp/gateway
    gateway:
      config:
        processors:
          batch: {}    # add this to prevent null
