# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Example configuration for sending data to your own OTLP HTTP backend
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.
##
#  exporters:
#    otlp_http/example:
#      endpoint: <your-endpoint-url>
#
#  service:
#    pipelines:
#      traces:
#        exporters: [spanmetrics, otlp_http/example]
exporters:
    otlphttp/elastic:
      endpoint: "elastic url"
      headers:
        Authorization: "ApiKey <api-key>"
service:
  pipelines:
    traces:
      exporters: [otlphttp/elastic, spanmetrics]  # Keep spanmetrics!
    metrics:
      exporters: [otlphttp/elastic]
    logs:
      exporters: [otlphttp/elastic]

